replicaCount: 1

image:
  repository: mariadb
  tag: "11"
  pullPolicy: IfNotPresent

mariadb:
  root:
    password: "password"
  database:
    user: "user"
    password: "userpassword"

service:
  type: NodePort
  port: 3306

persistentVolumeClaim:
  storage: 1Gi
