apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
spec:
  type: "{{ .Values.service.type }}"
  selector:
    app: mariadb
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 3306
