kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: mariadb-statefulset
  labels:
    app: mariadb
spec:
  serviceName: mariadb-service
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MARIADB_ROOT_PASSWORD
              value: "{{ .Values.mariadb.root.password }}"
            - name: MARIADB_USER
              value: "{{ .Values.mariadb.database.user }}"
            - name: MARIADB_PASSWORD
              value: "{{ .Values.mariadb.database.password }}"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mariadb-pvc
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mariadb-pvc
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: "{{ .Values.persistentVolumeClaim.storage }}"
